In [3]:
import numpy as np

In [4]:
np.random.rand(3)

array([0.39277428, 0.86078319, 0.62543163])

In [5]:
np.arange(2)

array([0, 1])

In [6]:
np.arange(2,3)

array([2])

In [7]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [8]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [9]:
np.random.rand(7)

array([0.96852468, 0.21240364, 0.29470381, 0.22954726, 0.75750687,
       0.22278638, 0.73802197])

In [10]:
np.random.randint(7,10,5)

array([7, 7, 7, 7, 8])

In [11]:
np.random.randint(30,40,5)

array([34, 38, 32, 33, 37])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros(4,dtype=int)


array([0, 0, 0, 0])

In [14]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.zeros((3,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [16]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
from numpy import *

In [22]:
a=np.random.randint(2)

In [23]:
a

1

In [24]:
arr=np.random.randint(0,100,(10,10))

In [25]:
arr

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [26]:
arr[2:3]

array([[38, 13, 77, 89,  6, 75, 81, 98, 43, 46]])

In [27]:
arr[:4]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59]])

In [28]:
arr[1,2]

85

In [29]:
arr[7,7]

50

In [30]:
arr

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [31]:
arr[1:2:3]

array([[45, 84, 85,  6, 33, 83, 64, 30, 99, 12]])

In [32]:
arr[1:4:2]

array([[45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59]])

In [34]:
arr[1:5:7]

array([[45, 84, 85,  6, 33, 83, 64, 30, 99, 12]])

In [ ]:
arr[7,7]# when we use comma n-1 rule is not followed

50

In [36]:
arr

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [37]:
arr[-5,-7]

43

In [39]:
arr[-5:-2]

array([[73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38]])

In [40]:
arr[:]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [41]:
arr[::-1]

array([[95, 52,  8, 39, 19, 64, 54, 90, 68, 79],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [53, 56, 93, 76, 44, 57, 57, 74, 89, 89]])

In [42]:
arr[::-2]

array([[95, 52,  8, 39, 19, 64, 54, 90, 68, 79],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12]])

In [43]:
arr[::2]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36]])

In [44]:
arr[::]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [45]:
arr[::]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [46]:
arr[:]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [47]:
arr[:2]

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12]])

In [48]:
arr[::-2]

array([[95, 52,  8, 39, 19, 64, 54, 90, 68, 79],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12]])

In [49]:
arr[::-1]

array([[95, 52,  8, 39, 19, 64, 54, 90, 68, 79],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [53, 56, 93, 76, 44, 57, 57, 74, 89, 89]])

In [50]:
arr.max()

99

In [51]:
arr.min()

0

In [52]:
arr.mean()

54.08

In [53]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [54]:
arr

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [55]:
arr.reshape(20,5)

array([[53, 56, 93, 76, 44],
       [57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33],
       [83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6],
       [75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39],
       [95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13],
       [28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29],
       [54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21],
       [93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42],
       [18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30],
       [79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19],
       [64, 54, 90, 68, 79]])

In [56]:
arr.reshape(50,2)

array([[53, 56],
       [93, 76],
       [44, 57],
       [57, 74],
       [89, 89],
       [45, 84],
       [85,  6],
       [33, 83],
       [64, 30],
       [99, 12],
       [38, 13],
       [77, 89],
       [ 6, 75],
       [81, 98],
       [43, 46],
       [79, 19],
       [64, 80],
       [39, 95],
       [ 4, 73],
       [94, 59],
       [23, 19],
       [81, 25],
       [13, 28],
       [36, 81],
       [50, 87],
       [73, 56],
       [80, 43],
       [29, 54],
       [43, 80],
       [60, 64],
       [85,  0],
       [87, 10],
       [21, 93],
       [37, 46],
       [65, 82],
       [53, 86],
       [17, 24],
       [42, 18],
       [17, 50],
       [86, 38],
       [ 9, 43],
       [77, 47],
       [30, 79],
       [34, 28],
       [74, 36],
       [95, 52],
       [ 8, 39],
       [19, 64],
       [54, 90],
       [68, 79]])

In [57]:
arr

array([[53, 56, 93, 76, 44, 57, 57, 74, 89, 89],
       [45, 84, 85,  6, 33, 83, 64, 30, 99, 12],
       [38, 13, 77, 89,  6, 75, 81, 98, 43, 46],
       [79, 19, 64, 80, 39, 95,  4, 73, 94, 59],
       [23, 19, 81, 25, 13, 28, 36, 81, 50, 87],
       [73, 56, 80, 43, 29, 54, 43, 80, 60, 64],
       [85,  0, 87, 10, 21, 93, 37, 46, 65, 82],
       [53, 86, 17, 24, 42, 18, 17, 50, 86, 38],
       [ 9, 43, 77, 47, 30, 79, 34, 28, 74, 36],
       [95, 52,  8, 39, 19, 64, 54, 90, 68, 79]])

In [60]:
arr[:,5]

array([57, 83, 75, 95, 28, 54, 93, 18, 79, 64])

In [58]:
mat=np.arange(0,100).reshape(10,10)

In [59]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
mat[4:6,4:9]

array([[44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [62]:
mat[2:8,6:7]

array([[26],
       [36],
       [46],
       [56],
       [66],
       [76]])

In [63]:
mat[4:6,2:7]

array([[42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56]])